Implement JSON parser for upcoming structured logging
input-output-hk/log-classifier pull request #65
Opened 2018-09-18 09:07 UTC by HirotoShioi

Youtrack: https://iohk.myjetbrains.com/youtrack/issue/TSD-141

Still in WIP!

2018-09-19 03:47 UTC, HirotoShioi commented
I guess 1 more thing I could do is to wrap the decoded log file with newtype instead of raw `ByteString`

2018-09-20 03:00 UTC, HirotoShioi commented
From what I heard from Kristijan, structure of logging might have few changes.
Let's not merge this until that is settled.

2018-09-20 09:26 UTC, ksaric requested changes
There are some changes required.

2018-09-20 09:26 UTC, ksaric commented on src/LogAnalysis/Classifier.hs
> +extractIssuesFromLogs :: (MonadCatch m) => [(FilePath, ByteString)] -> Analysis -> m Analysis
Propagating `FilePath` might be a bit misleading. What we really want to propagate is:
```
data LogFormat = Txt | JSON
```

And also, almost as if `(FilePath, ByteString)` gets propagated through the codebase. As if... As if it's important enough to be wrapped in a newtype :wink:

2018-09-20 09:26 UTC, ksaric commented on src/LogAnalysis/Classifier.hs
> +    extractMessagesPlain c = do
What is `c`? Please don't use abbreviations unless you must. And you never really have to.

2018-09-20 09:26 UTC, ksaric commented on src/LogAnalysis/Classifier.hs
> +            let errorText = P.head $ lefts decodedLogLines
`safeHead`, using a total function (if I remember correctly you were saying that non-total functions are pure evil) and then `maybe` or simple case.

2018-09-20 09:26 UTC, ksaric commented on src/LogAnalysis/Types.hs
> +data CardanoLog = CardanoLog {
Leave `clLog` on but simply put it as optional, using `Maybe`, like `clHost` has to be.

2018-09-20 09:26 UTC, ksaric commented on src/Util.hs
> +    let extractedStrictLog = map (\(path, content) -> (path, LBS.toStrict content)) extractedLog
Here is a nice place where you can use `where` (`\(path, content) -> (path, LBS.toStrict content)`)and check if the filetype is "txt" or "json".

2018-09-20 09:26 UTC, ksaric commented on test/LogAnalysisSpec.hs
> +genErrorText = elements
Nice idea, something I was planning to add as well.

2018-09-20 09:26 UTC, ksaric commented on test/LogAnalysisSpec.hs
> +genKnowledgeWithErrorText eText = do
I'm sure you thought about that, but it is possible but unlikely, to hit a collision with some existing issue.
You can simply remove those if they ever appear. `... shouldBe . not . elem ... `

2018-09-20 09:26 UTC, ksaric commented on test/LogAnalysisSpec.hs
> +encodedElements :: [Text] -> Gen ByteString
Put this in a `where` condition of the function it's used in. Otherwise, people need to think about what it does (on the top level).

2018-09-20 09:26 UTC, ksaric commented on test/LogAnalysisSpec.hs
> +showIso8601 :: UTCTime -> String
Put in `where`.

2018-09-20 09:26 UTC, ksaric commented on test/LogAnalysisSpec.hs
> +genJSONWithError :: Text -> Gen (FilePath, ByteString)
This is where the type description would come in handy. You don't need to deal with `ByteString` but add a `LogType` and you can have a single generator.
Also, remove the `Text` parameter and generate it in the function.

2018-09-20 09:26 UTC, ksaric commented on test/LogAnalysisSpec.hs
> +genLogJSONFilePath :: Gen FilePath
Add generator for `LogType` and then you add a single test that tests `FilePath -> LogType` with a single generator.

2018-09-20 09:26 UTC, ksaric commented on src/LogAnalysis/Types.hs
> +    parseJSON = withObject "Cardano node log" $ \o -> do
Are you sure the object is called `"Cardano node log"` ?

2018-09-20 09:26 UTC, ksaric commented on test/LogAnalysisSpec.hs
> +            forAll ((,) <$> genLogJSONFilePath <*> genJSONLogFile)
Please don't use `(,) <$> genLogJSONFilePath <*> genJSONLogFile` - unless it's a very specific distinction that the reader needs to take a look at, I'm not interested in the distinction between `Applicative` and `Monad` and it's killing readability.
For example, I would understand you use this if you have some concurrency code that uses `Applicative` and you want to explain that the things inside it are not related, but in most cases this is not an issue.

2018-09-20 09:26 UTC, ksaric commented on test/LogAnalysisSpec.hs
> +genLogText mErrorText = do
This is ok, but we are still missing the test for the JSON serialization roundtrip. Shouldn't be too hard to add - you need to test if `decode . encode` is the same thing you sent it to.

2018-09-20 09:26 UTC, ksaric commented on src/LogAnalysis/Classifier.hs
> +        let logLines = C8.lines c
This is strange. Something we need to discuss with the guys about the logging format.

2018-09-20 09:26 UTC, ksaric commented on test/LogAnalysisSpec.hs
> +genLogWithError :: Text -> Gen (FilePath, ByteString)
Remove `Text` param and handle both cases. Single generator, test case that covers multiple cases.

2018-09-21 04:12 UTC, HirotoShioi commented on src/LogAnalysis/Classifier.hs
> +extractIssuesFromLogs :: (MonadCatch m) => [(FilePath, ByteString)] -> Analysis -> m Analysis
I agree. 
In that case, I'll define an datatype `LogFile` which takes `FileFormat` and `ByteString` as argument.

2018-09-21 04:28 UTC, HirotoShioi commented on test/LogAnalysisSpec.hs
> +genLogText mErrorText = do
Ah, I see. I can add that.

2018-09-21 04:30 UTC, HirotoShioi commented on src/LogAnalysis/Classifier.hs
> +        let logLines = C8.lines c
Okay! Please let me know how the discussion goes!

2018-09-21 06:07 UTC, HirotoShioi commented on test/LogAnalysisSpec.hs
> +genLogWithError :: Text -> Gen (FilePath, ByteString)
Well, I want to be able to test both cases where I can actually catch the errorText and can't find anything at all which means I need to be able to have some control of how the content of a file should be.
I changed it to take `Maybe Text` as an argument instead. If it's not what you're expecting, then I'll fix it.

2018-09-21 06:13 UTC, HirotoShioi commented on test/LogAnalysisSpec.hs
> +            forAll ((,) <$> genLogJSONFilePath <*> genJSONLogFile)
Fixed!

2018-09-21 08:02 UTC, HirotoShioi commented on test/LogAnalysisSpec.hs
> +genLogJSONFilePath :: Gen FilePath
Ah I finally understood what you mean. I'll add test next week.

2018-09-21 08:14 UTC, HirotoShioi commented
Note to myself.
Need test on `toLogFile` to see if it actually distinguishes the file correctly.

2018-09-24 10:41 UTC, ksaric commented on src/LogAnalysis/Types.hs
> +data FileFormat
`(LogFile lfContent * FileFormat) + (LogFile lfContent * FileFormat)` == `(LogFile lfContent + LogFile lfContent) * FileFormat` == `(LogFile lfContent * (1 + 1)) * FileFormat` == `(2 * LogFile lfContent) * FileFormat` == `2 * (LogFile lfContent * FileFormat)`

2018-09-24 10:42 UTC, ksaric commented on src/LogAnalysis/Types.hs
> +data FileFormat
Will fix/simplify for example.

2018-09-24 12:00 UTC, ksaric approved these changes
LGTM.

2018-09-24 12:02 UTC, ksaric commented
Merging since I want to rebase my work on top of this to merge all open PRs and move on with our work.

2018-09-24 12:02 UTC, merged