[TSD-145] Remove unused modules and features
input-output-hk/log-classifier pull request #70
Opened 2018-09-27 08:42 UTC by HirotoShioi

YT issue: https://iohk.myjetbrains.com/youtrack/issue/TSD-145

2018-09-28 08:27 UTC, ksaric approved these changes
LGTM.

2018-09-28 08:27 UTC, ksaric commented on src/DataSource/Types.hs
> +    { cfgAgentId            :: !UserId
Nice.

2018-09-28 08:30 UTC, ksaric requested changes
Fix test.

2018-10-02 02:54 UTC, HirotoShioi commented
@ksaric Will do. Thank you!

2018-10-02 03:34 UTC, HirotoShioi commented
I've finished adding Haddock comments. The project now has decent coverage.

2018-10-02 09:21 UTC, ksaric approved these changes
Very nice work!

2018-10-02 11:21 UTC, merged